global:
  name: consul
  datacenter: dc1
server:
  replicas: 3
ui:
  enabled: true
  service:
    type: 'LoadBalancer'
connectInject:
  enabled: true
controller:
  enabled: true
syncCatalog:
  enabled: false
